repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.4
  hooks:
    - id: ruff
      args: ["--fix"]
      exclude: "codegen/templates/.*"
    - id: ruff-format
      exclude: "codegen/templates/.*"
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.400
  hooks:
  - id: pyright
    name: pyright
    files: "src/.*"
