
name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:

    defaults:
      run:
        shell: bash
    environment: CI
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12', '3.13', '3.14.0-beta.2']
        python-arch: [x64]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}-${{ matrix.python-arch }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}

    - name: Install Poetry
      uses: snok/install-poetry@v1.4.1

    - name: Initialize Submodules
      run: |
        git submodule update --init --recursive

    - name: Install
      run: |
        poetry install
      env:
        EGEOMETRY_BUILD_WITH_COVERAGE: ${{ matrix.os == 'windows-latest' && '0' || '1' }}

    - name: Test
      run: |
        poetry run pytest --cov=egeometry --cov-report=xml

    - name: Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  static-analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
        architecture: x64

    - name: Install Poetry
      uses: snok/install-poetry@v1.4.1
      with:
        virtualenvs-in-project: true

    - name: Initialize Submodules
      run: |
        git submodule update --init --recursive

    - name: Install
      run: |
        poetry install

    - name: Upgrade pip & setuptools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools

    - name: Install Pre-Commit
      run: |
        python -m pip install pre-commit

    - name: Static Analysis
      run: |
        python -m pre_commit run --all-files
